/**
 * 前端统一文案字典：
 * 所有用户可见文本优先从此处读取，避免页面散落硬编码字符串。
 */
export const copy = {
  brand: {
    title: "LuLu-Polymarket",
    description: "LuLu-Polymarket（ETH 抵押）",
    menuTitle: "导航"
  },
  common: {
    yes: "是",
    no: "否",
    unknown: "未知",
    invalidOutcome: "结果无效",
    eventIdInvalid: "无效事件 ID。",
    eventNotFound: "未找到该事件。",
    loadingEventData: "正在加载事件数据...",
    loadingEvents: "正在加载事件...",
    loadingWalletState: "正在加载钱包状态...",
    currentWallet: (value: string) => `当前钱包：${value}`,
    resolverAddress: (value: string) => `结果裁定员（resolver）：${value}`,
    eventNumber: (value: string) => `事件 #${value}`,
    closeTimeLabel: "可提交结果时间",
    totalPool: "总奖池",
    shareUnit: "份",
    ethUnit: "ETH",
    retry: "重新加载",
    retryLater: "请稍后重试。",
    noData: "--",
    close: "关闭",
    networkNot31337: "当前网络不是 31337，请先切换网络。",
    switchToLocalChain: "请先切换到本地测试网。",
    localChain: (chainId: number) => `本地测试网 ${chainId}`,
    submitting: "提交中..."
  },
  labels: {
    eventStateOpen: "交易中",
    eventStateClosed: "已截止（兼容态）",
    eventStateProposed: "待确认",
    eventStateResolved: "已结算",
    outcomeUnresolved: "未判定"
  },
  nav: {
    events: "事件",
    resolve: "事件结算",
    create: "创建事件",
    openMenu: "打开菜单"
  },
  footer: {
    copyright: "© 2026 lllu_23 · LuLu-Polymarket",
    github: "GitHub"
  },
  wallet: {
    connect: "连接钱包",
    connecting: "连接中...",
    noWalletDetected: "未检测到钱包",
    wrongNetwork: (chainId: number) => `网络不匹配（当前 ${chainId}）`
  },
  config: {
    notReadyTitle: "系统尚未初始化",
    notReadyBody: "当前系统尚未完成本地部署，暂时不可用。请先完成部署后刷新页面。"
  },
  eventCard: {
    coverAlt: (question: string) => `${question} 封面图`,
    noCover: "暂无封面",
    closeTime: (value: string) => `可提交结果时间：${value}`,
    poolSize: (value: string) => `池子规模：${value}`,
    openEvent: "进入事件"
  },
  eventsPage: {
    title: "事件大厅",
    overviewTitle: "账户概览",
    overviewSubtitle: "查看本地测试网资金、参与进度与事件活跃度。",
    balanceLabel: "本地测试网 ETH 余额",
    participatedLabel: "参与事件数量",
    claimableLabel: "可赎回总额",
    eventStatsLabel: "交易中事件 / 总事件",
    eventStatsValue: (open: number, total: number) => `${open} / ${total}`,
    connectHint: "连接钱包后可查看你的个人指标。",
    allTag: "全部",
    loadFailed: (reason: string) => `事件列表读取失败：${reason}`,
    emptyAll: "暂无符合标签规则的事件。",
    emptyByTag: (tag: string) => `暂无“${tag}”标签事件。`
  },
  createPage: {
    title: "创建事件",
    subtitle: "仅管理员可创建事件。连接钱包后将自动校验权限。",
    needConnect: "请先连接钱包，以校验管理员权限。",
    checkingOwner: "正在校验管理员权限，请稍候...",
    checkFailed: "权限校验失败",
    cannotReadOwner: "暂时无法读取管理员地址，请检查本地服务后重试。",
    noPermission: "无权限访问",
    ownerOnly: "仅管理员可访问该页面并创建事件。",
    ownerAddress: (value: string) => `管理员地址：${value}`
  },
  createForm: {
    title: "创建事件",
    cockpitTitle: "创建驾驶舱",
    cockpitDesc: "在一个界面内完成事件定义、资料准备与提交前确认。",
    adminAndResolver: (owner: string, resolver: string) => `管理员：${owner} · 结果裁定员：${resolver}`,
    networkHint: "当前不在本地测试网，请先切换网络。",
    ownerLabel: "管理员",
    resolverLabel: "结果裁定员",
    networkLabel: "网络状态",
    networkReady: "已连接本地测试网",
    networkBlocked: "需切换到本地测试网",
    formReady: "可提交",
    formBlocked: "待完善",
    basicGroupTitle: "基础信息",
    basicGroupDesc: "先定义事件问题和时间窗口。",
    eventQuestion: "事件问题（一句话）",
    eventQuestionPlaceholder: "例如：本周五前 ETH 会高于 5000 美元吗？",
    closeDuration: "可提交结果时长（例如：30s）",
    closeDurationPlaceholder: "例如：30s",
    durationPresets: "快捷时长",
    durationInputHint: "请输入秒级时长，格式如 30s。",
    firstSubmitTime: (time: string) => `预计可提交结果时间：${time}`,
    firstSubmitTimeFallback: "预计可提交结果时间：输入有效时长后自动计算。",
    firstFinalizeTime: (time: string) => `预计最早确认结果时间：${time}（提交后进入 30 秒冷静期）`,
    firstFinalizeTimeFallback: "预计最早确认结果时间：输入有效时长后自动计算。",
    rulesUri: "判定规则链接（可选）",
    rulesUriPlaceholder: "例如：https://example.com/rules（可留空）",
    metadataGroupTitle: "事件资料",
    metadataGroupDesc: "可直接填写资料链接，或本地上传生成资料。",
    metadataMode: "事件资料填写方式",
    metadataByUri: "直接填写资料链接",
    metadataLocalBuild: "本地生成资料",
    metadataUriLabel: "事件资料链接（Metadata URI）",
    metadataUriPlaceholder: "例如：ipfs://xxx 或 https://xxx.json",
    localTitle: "事件标题",
    localTitlePlaceholder: "例如：美国 2028 大选结果预测",
    localDescription: "事件描述",
    localDescriptionPlaceholder: "输入事件背景、判定规则与注意事项...",
    localTag: "事件标签",
    coverImage: "封面图（PNG/JPEG/WEBP，≤ 5MB）",
    extraInfo: "补充信息（可选，页面展示用）",
    addField: "新增字段",
    fieldKeyPlaceholder: "字段名（例如：数据来源）",
    fieldValuePlaceholder: "字段值（例如：官方公告）",
    deleteField: "删除",
    submitGroupTitle: "提交创建",
    submitGroupDesc: "完成校验后发起链上创建交易。",
    connectRequired: "连接钱包后才能发起交易。",
    validatingMetadata: "正在校验资料...",
    creating: "创建中...",
    createEvent: "创建事件",
    previewTitle: "事件预览",
    previewDesc: "根据当前输入实时渲染展示效果。",
    previewQuestion: "事件问题",
    previewQuestionFallback: "尚未填写事件问题",
    previewTag: "事件标签",
    previewMode: "资料模式",
    previewMetadataUri: "资料链接",
    previewRulesUri: "判定规则",
    previewRulesFallback: "未设置",
    previewCoverFallback: "暂无封面预览",
    timelineTitle: "时间轴预览",
    timelineDesc: "创建后将基于当前时间进入结算流程。",
    timelineNow: "当前时间",
    timelineSubmit: "可提交结果时间",
    timelineFinalize: "最早确认结果时间",
    fieldChecks: "字段完成度",
    fieldCheckQuestion: "事件问题",
    fieldCheckDuration: "时长格式",
    fieldCheckMetadata: "资料完整性",
    statusReady: "已就绪",
    statusPending: "待完善"
  },
  createValidation: {
    titleRequired: "事件标题不能为空。",
    descriptionRequired: "事件描述不能为空。",
    invalidExtraFields: "事件资料填写有误，请检查后重试。",
    coverImageRequired: "请上传封面图。",
    coverImageEmpty: "封面图文件为空，请重新选择。",
    coverImageTooLarge: "封面图不能超过 5MB。",
    coverImageTypeNotAllowed: "封面图格式仅支持 PNG/JPEG/WEBP。",
    invalidCategory: "事件标签仅支持“金融”或“体育”。",
    metadataFetchFailed: "事件资料读取失败，请检查资料链接是否可访问。",
    invalidMetadataJson: "事件资料不是有效 JSON。",
    uriRequired: "事件资料链接不能为空。",
    invalidUri: "事件资料链接格式不正确。",
    metadataProcessFailed: "事件资料处理失败，请稍后重试。",
    rowMissingKey: "有一行只填了内容没填字段名，请补全。",
    duplicatedExtraField: (field: string) => `补充信息字段重复：${field}`,
    extraFieldInvalid: "补充信息填写有误。",
    metadataUriMissingFromApi: "事件资料生成失败：未返回资料链接。",
    metadataUploadFailed: "事件资料上传失败，请稍后重试。",
    metadataReadFailed: "事件资料读取失败，请稍后重试。",
    questionRequired: "问题不能为空。",
    closeDurationTooShort: "可提交结果时长不能小于 30s。",
    closeDurationTooLong: "可提交结果时长不能超过 30天。"
  },
  resolveList: {
    title: "事件结算",
    subtitle: "仅结果裁定员（resolver）可提交结果并确认结果；冷静期为 30 秒。",
    guideTitle: "结算说明",
    guideDescription: "该页面用于选择需要执行结算的事件。",
    guideTail: "非裁定员也可查看本页，但无法在结算页执行操作。",
    noConnect: "你尚未连接钱包。连接后可自动校验是否为结果裁定员。",
    wrongNetworkBanner: "当前不在本地测试网，请先切换到 Anvil（31337）。",
    emptyEvents: "暂无事件可结算。",
    finalOutcome: "结算结果",
    openResolvePage: "进入结算页",
    viewDetail: "查看详情"
  },
  resolvePage: {
    title: "事件结算页（Resolver 专用）",
    subtitle: "仅结果裁定员（resolver）可执行“提交结果”和“确认结果”。",
    cockpitTitle: "结算驾驶舱",
    cockpitDesc: "查看结算状态、时间轴并执行提交结果/确认结果操作。",
    eventQuestionLabel: "事件问题",
    currentState: (value: string) => `当前状态：${value}`,
    closeTime: (value: string) => `可提交结果时间：${value}`,
    finalOutcomeLabel: "事件最终结果",
    finalOutcome: (value: string) => `事件最终结果：${value}`,
    proposedOutcomeLabel: "提案结果",
    proposedAtLabel: "提案时间",
    resolverPermissionLabel: "裁定权限",
    resolverPermissionGranted: "当前钱包可执行结算操作",
    resolverPermissionDenied: "当前钱包不可执行结算操作",
    ready: "已就绪",
    pending: "待满足",
    timelineTitle: "结算时间轴",
    timelineDesc: "时间轴基于链上状态与本地时钟实时展示。",
    timelineNow: "当前时间",
    timelineClose: "可提交结果时间",
    timelineProposedAt: "提案时间",
    timelineCanFinalizeAt: "最早确认时间",
    checksTitle: "操作就绪度",
    checkResolver: "裁定权限",
    checkCanPropose: "可提交结果",
    checkCanFinalize: "可确认结果",
    overviewTitle: "结算概览",
    overviewDesc: "聚合事件状态、提案与最终确认状态。",
    backToDetail: "返回事件详情",
    backToResolveList: "返回结算列表",
    needConnect: "请先连接钱包，以校验结果裁定员权限。",
    checkingResolver: "正在校验结果裁定员权限，请稍候...",
    resolverReadFailed: "暂时无法读取 resolver 地址，请检查本地服务后重试。",
    noPermission: "无权限访问",
    noPermissionBody: "仅结果裁定员（resolver）可在该页面执行事件结算。",
    actionsTitle: "结算操作",
    actionsDesc: "流程：提交结果 → 等待 30 秒冷静期 → 确认结果。",
    proposalStatus: "提案状态",
    finalizedStatus: "结果确认状态",
    proposed: (outcome: string) => `已提案（${outcome}）`,
    notProposed: "未提案",
    finalized: "已确认",
    readyToFinalize: "可确认",
    notFinalized: "未确认",
    canFinalizeAt: "最早确认时间",
    cooldown: "冷静期倒计时",
    counting: "计算中...",
    cooldownSeconds: (seconds: number) => `${seconds} 秒`,
    submitYes: "提交“是”结果",
    submitNo: "提交“否”结果",
    submitInvalid: "提交无效结果",
    finalize: "确认结果"
  },
  eventDetail: {
    tradeDesk: "交易驾驶舱",
    tradeDeskDesc: "在一个模块内完成概率观察、持仓查看和买入操作。",
    cannotBuy: (stateLabel: string) => `当前不可买入：事件状态为 ${stateLabel}。`,
    myYes: "我的“是”持仓",
    myNo: "我的“否”持仓",
    holdingOverview: "持仓总览",
    totalShares: (value: string) => `总计 ${value} 份`,
    holdingRatio: "持仓占比",
    poolRatioNote: "按奖池占比展示",
    emptyPoolRatioNote: "当前空池，默认显示 50/50",
    impactSim: "交易影响模拟",
    impactSimDesc: "基于当前池子静态估算",
    realtime: "实时",
    baseline: "当前基线",
    ifBuyYes: "若买入“是”",
    ifBuyNo: "若买入“否”",
    afterBuyPool: "买后池子",
    afterBuyProb: "买后概率",
    change: "变化",
    simulationHint: "输入有效 ETH 金额后可查看买入影响（并发交易不会计入该估算）。",
    buyAmount: "买入金额（ETH）",
    buyPrefix: "买入",
    buyAmountPlaceholder: "例如 0.1",
    buyYes: "买入“是”",
    buyNo: "买入“否”",
    eventSnapshot: (total: string, winner: string) => `结算快照：总池 ${total} ETH，赢家池 ${winner} ETH`,
    finalOutcome: (value: string) => `结算结果：${value}`,
    backToHall: "返回事件大厅",
    openResolvePage: "进入结算页",
    buySuccessYes: (amount: string) => `已买入“是”：${amount} ETH`,
    buySuccessNo: (amount: string) => `已买入“否”：${amount} ETH`,
    redeemSubmitted: "赎回交易已提交，等待链上确认。",
    redeemTitle: "结算赎回",
    redeemDesc: "按结算结果展示可赎回份额与兑付预估；Yes/No 仅赢家方向可赎回，Invalid 支持全量赎回。",
    settlementInfo: "链上结算信息",
    proposedOutcome: "提案结果",
    proposer: "提案人",
    finalizedState: "结果确认状态",
    proposedAt: "提案时间",
    canFinalizeAt: "最早确认时间",
    totalSnapshot: "总池快照",
    winningSnapshot: "赢家池快照",
    myPositionRedeemable: "我的持仓与可赎回份额",
    positionYes: "持仓：是",
    positionNo: "持仓：否",
    redeemable: (value: string) => `可赎回：${value} 份`,
    redeemPreview: (value: string) => `可兑付预估：${value} ETH`,
    oneClickRedeem: "一键全赎回",
    noRedeemableForOutcome: (outcome: string) => `当前结果为“${outcome}”，但你没有可赎回份额，仅展示结算信息。`,
    redeemWinningShares: (winner: string) => `赎回“${winner}”份额`,
    redeemPlaceholder: (max: string) => `最多 ${max} 份`,
    redeemEth: "赎回 ETH",
    noWinnerShares: (outcome: string, winner: string) => `当前结果为“${outcome}”，你没有“${winner}”份额可赎回，仅展示结算信息。`,
    winnerFallback: "赢家",
    recentActivity: "最近活动",
    recentActivityDesc: "仅展示链上可读事件（含买入方向与买后池子快照）。",
    noActivity: "暂无活动记录。",
    boughtUser: "买入用户",
    boughtSide: "买入方向",
    spentAmount: "本次投入",
    mintedShares: "铸造份额",
    poolSnapshotAfterBuy: "买入后事件仓位快照",
    blockNumber: (value: string) => `区块 #${value}`,
    account: (value: string) => `账户：${value}`,
    amount: (value: string) => `数量：${value}`,
    result: (value: string) => `结果：${value}`
  },
  eventActivityKind: {
    event_created: "创建事件",
    position_bought: "买入头寸",
    resolution_proposed: "提交结果",
    resolution_finalized: "确认结果",
    redeemed: "赎回"
  },
  errors: {
    eventActions: {
      systemNotReady: "系统未准备好，请先连接钱包并确认本地环境。",
      txReverted: "交易已上链但执行失败（reverted）。请检查当前事件状态后重试。",
      invalidBuyAmount: "请输入正确的买入金额（单位：ETH，例如 0.1）。",
      invalidRedeemAmount: "请输入正确的赎回数量（单位：份）。",
      redeemAmountBothZero: "赎回数量不能同时为 0（单位：份）。",
      txFailed: (reason: string) => `交易失败：${reason}`,
      txFailedFallback: "交易失败，请在钱包中确认并稍后重试。"
    },
    createEvent: {
      systemNotReady: "系统尚未初始化，暂时不能创建事件。",
      closeDurationTooShort: "可提交结果时长不能小于 30s。",
      closeDurationTooLong: "可提交结果时长不能超过 30天。",
      ownerOnly: "仅管理员可创建事件。",
      questionRequired: "事件问题不能为空。",
      endTimePast: "可提交结果时间已过，请调整后重试。",
      userRejected: "你已取消签名，创建未提交。",
      fallback: "创建失败，请检查输入内容并在钱包中确认交易。",
      eventIdNotResolved: "创建交易已确认，但未解析到事件 ID。已返回事件列表，请在列表中查看新事件。"
    }
  }
} as const;
