// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/collaborator" | "/creator" | "/creator/claim" | "/creator/history" | "/ledger" | "/platform" | "/platform/history" | "/platform/results"
type AppRouteHandlerRoutes = "/api/collaborator/receipts" | "/api/creator/bill/current" | "/api/creator/claim-package" | "/api/creator/history" | "/api/ledger" | "/api/platform/activity" | "/api/platform/batches/current" | "/api/platform/batches/publish" | "/api/platform/history" | "/api/platform/monthly-configs" | "/api/platform/monthly-configs/commit" | "/api/platform/reserve/status" | "/api/tx/receipt"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/collaborator/receipts": {}
  "/api/creator/bill/current": {}
  "/api/creator/claim-package": {}
  "/api/creator/history": {}
  "/api/ledger": {}
  "/api/platform/activity": {}
  "/api/platform/batches/current": {}
  "/api/platform/batches/publish": {}
  "/api/platform/history": {}
  "/api/platform/monthly-configs": {}
  "/api/platform/monthly-configs/commit": {}
  "/api/platform/reserve/status": {}
  "/api/tx/receipt": {}
  "/collaborator": {}
  "/creator": {}
  "/creator/claim": {}
  "/creator/history": {}
  "/ledger": {}
  "/platform": {}
  "/platform/history": {}
  "/platform/results": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
