// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/collaborator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collaborator">> = Specific
  const handler = {} as typeof import("../../../app/collaborator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/creator/claim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/claim">> = Specific
  const handler = {} as typeof import("../../../app/creator/claim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/creator/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/history">> = Specific
  const handler = {} as typeof import("../../../app/creator/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/creator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator">> = Specific
  const handler = {} as typeof import("../../../app/creator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ledger">> = Specific
  const handler = {} as typeof import("../../../app/ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/platform/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/history">> = Specific
  const handler = {} as typeof import("../../../app/platform/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform">> = Specific
  const handler = {} as typeof import("../../../app/platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/platform/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/results">> = Specific
  const handler = {} as typeof import("../../../app/platform/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/collaborator/receipts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collaborator/receipts">> = Specific
  const handler = {} as typeof import("../../../app/api/collaborator/receipts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/creator/bill/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creator/bill/current">> = Specific
  const handler = {} as typeof import("../../../app/api/creator/bill/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/creator/claim-package/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creator/claim-package">> = Specific
  const handler = {} as typeof import("../../../app/api/creator/claim-package/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/creator/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creator/history">> = Specific
  const handler = {} as typeof import("../../../app/api/creator/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ledger/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ledger">> = Specific
  const handler = {} as typeof import("../../../app/api/ledger/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/activity">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/batches/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/batches/current">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/batches/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/batches/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/batches/publish">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/batches/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/history">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/monthly-configs/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/monthly-configs/commit">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/monthly-configs/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/monthly-configs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/monthly-configs">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/monthly-configs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/reserve/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/reserve/status">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/reserve/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/tx/receipt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tx/receipt">> = Specific
  const handler = {} as typeof import("../../../app/api/tx/receipt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
